# Application Name
spring.application.name=ai-interview-preparation


# Server Port
server.port=${PORT:9080}


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:h2:mem:interview_prep
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Gemini Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.0-flash